### ISSUE TITLE
keep.pairScore option is time consuming

### ISSUE THREAD

**Issue by eusebe** [bozenne/BuyseTest#1]
Hi,
Thank you for this very complete package!
After playing with it, I noticed that the keep.pairScore option seems surprisingly time consuming.
Is it an issue that may be corrected?

Best regards, 
David

```
> df <- simBuyseTest(n.T = 500, n.C = 500)
> time1 <- system.time(BuyseTest(data = df,
                      endpoint = "eventtime",
                      type = "timeToEvent",
                      censoring = "status",
                      treatment = "Treatment",
                      method.inference = "none", 
                      method.tte = "Gehan", 
                      keep.pairScore = FALSE))[3]
> time2 <- system.time(BuyseTest(data = df,
                      endpoint = "eventtime",
                      type = "timeToEvent",
                      censoring = "status",
                      treatment = "Treatment",
                      method.inference = "none", 
                      method.tte = "Gehan", 
                      keep.pairScore = TRUE))[3]
> time2/time1
elapsed 
     12 
```

**Comment by bozenne** [comment]
Hi, yes to me it is quite normal that keep.pairScore makes it slower 
since it stores the results of all pairwise comparisons. So in your example it create a table with 250 000 rows. It is meant for debugging and also to help the user to understand what BuyseTest is doing (on on small examples). So unless there is a good reason, I don't really plan to make it faster.

Note: Looking at it more closely with profvis, I see that the C++ code is a 6x slower (180ms instead of 30ms)
but in fact it is the R function that I have written to reorganize the results afterward that is quite slow (600ms - probably could be improved)

Regards
brice
