### ISSUE TITLE
error with large dataset

### ISSUE THREAD

**Issue by kan-li** [bozenne/BuyseTest#5]
Hi,
Thank you very much for developing this helpful package!
When I try to apply BuyseTest to a large dataset, for example, 10000 subjects, I get the error

error: Mat::init(): requested size is too large
Error in GPC_cpp(endpoint = envir$outArgs$M.endpoint, status = envir$outArgs$M.status,  : 
  Mat::init(): requested size is too large
Calls: BuyseTest -> .BuyseTest -> GPC_cpp -> .Call
Execution halted

I run the code on HPC  memory should not be an issue. I did a quick search online and feel it may work for defining ARMA_64BIT_WORD for use of large matrix in rcpp. Could you please investigate this? Thank you very much!

**Comment by bozenne** [comment]
Thanks!
Humm normally BuyseTest should not be very demanding in memory EXCEPT when if you use the option method.inference="u-statistic" with scoring.rule="Peron".

For instance this:
```
library(BuyseTest)
library(profvis)
set.seed(10)
d <- simBuyseTest(5000) ## 10 000 subjects (two groups of 5 000

p <- profvis(
    e.BT <- BuyseTest(treatment ~ tte(eventtime, status, threshold = 1),
                      data = d,
                      scoring.rule = "Peron", method.inference = "none")
)

p
```
runs on my standard laptop (according to profvis it takes 30s and 24 MB).
Can you also run that?

If yes, how did you called BuyseTest when it crashed?
Also what is the version of BuyseTest you used?

Best regards
brice

**Comment by kan-li** [comment]
The code could run as expected after setting the inference to none.  
I will try doing the inference using re-sampling approach with more computing resources. Hopefully that would not be too computationally prohibitive.  
Thank you very much!

**Comment by bozenne** [comment]
Great. Yes the current implementation of method.inference="u-statistic" with scoring.rule="Peron" does not scale well (at all). 
I will work on that in the new version. Until then you can method.inference="bootstrap".

**Comment by bozenne** [comment]
Hi,

Just for your information, I have pushed a new version on Github (1.9.0, branch master) where you should not have anymore memory issue when using method.inference="u-statistic" with scoring.rule="Peron".
However with large sample sizes, BuyseTest is not very fast. For instance:
`
library(BuyseTest)
set.seed(10)
d <- simBuyseTest(5000) ## 10 000 subjects (two groups of 5 000)

system.time(
    e.BT <- BuyseTest(treatment ~ tte(eventtime, status, threshold = 1) + bin(toxicity) + tte(eventtime, status, threshold = 0),
                      data = d,
                      scoring.rule = "Peron", method.inference = "u-statistic")
)
`

took about 80 min (roughly equivalent to the time it takes to obtain 30 bootstrap samples).
Part of the complexity is due to the underlying survival model, which has one parameter at each event time so if you have many events that will slow down the code.

**Comment by kan-li** [comment]
Many thanks! I will try it！
