### ISSUE TITLE
powerBuyseTest with Gehan statistic

### ISSUE THREAD

**Issue by graemeleehickey** [bozenne/BuyseTest#6]
The following code throws an error:

```r
library(BuyseTest)

args <- list(rates.T = c((3:5) / 10), rates.Censoring.T = rep(1, 3))

simFCT <- function(n.C, n.T) {
  simBuyseTest(100, argsBin = NULL, argsCont = NULL, argsTTE = args)
}

powerBuyseTest(sim = simFCT, sample.size = c(100), n.rep = 2,
               formula = treatment ~ tte(eventtime1, status = status1),
               method.inference = "u-statistic",
               scoring.rule = "Gehan")
```

The error is `r Error in FUN(X[[i]], ...) : argument "censoring" is missing, with no default`.

For some reason the code works with if I change `r status = status1` to `r censoring = status1`. In my view, this case should throw an error message.

**Comment by graemeleehickey** [comment]
One other minor thing: if you set `trace = 4` in the above, you also get an error message of:

```r
Error in unique(M.status[, iC]) : 
  argument "M.status" is missing, with no default
```

**Comment by bozenne** [comment]
Thanks! This first bug is because I forgot to update powerBuyseTest() when I created two separate arguments in BuyseTest():
- status: variable in data containing the type of event (0 censoring, 1 event of interest, 2 time to event)
- censoring: type of censoring ("left" or "right" , "left" is only supported with the Gehan's scoring rule.
So the code you wrote should work; but not when using censoring = status1.
I will corrected that, as well as the other issue,  in the new version (1.9.0)
I let you know when it is available.

**Comment by bozenne** [comment]
So I have pushed a new version of BuyseTest (1.9.0) that should fix both bugs.
Note that if you would like to use several CPUs to run the simulation you need to slightly modify you simFCT: 
`
simFCT2 <- function(n.C, n.T) {
    args <- list(rates.T = c((3:5) / 10), rates.Censoring.T = rep(1, 3))
    simBuyseTest(100, argsBin = NULL, argsCont = NULL, argsTTE = args)
}

xx <- powerBuyseTest(sim = simFCT2, sample.size = c(100), n.rep = 100, cpus = 3,
                     formula = treatment ~ tte(eventtime1, status = status1),
                     method.inference = "u-statistic",
                     scoring.rule = "Gehan", trace = 4)
summary(xx)
`
(otherwise args is in the global environment, which is not (explicitly) transferred to each CPUs, so running simFCT2 may fail.)
